---
title: "Load MRICloud Output"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE)
library(flexdashboard)
library(tidyverse)
library(MRIcloudT1volumetrics)

```


input data {.sidebar}
===

```{r}
fileInput("imageFiles", "Select input image txt files file, use CTRL or Shift to select multiple files.", 
                 multiple = TRUE)

checkboxGroupInput(inputId = "levels", 
                   label = "Select level(s)",
                   choiceNames = as.character(1 : 5),
                   choiceValues = 1 : 5,
                   selected = 1 : 5)

checkboxGroupInput(inputId = "types", 
                   label = "Select types(s)",
                   choiceNames = as.character(1 : 2),
                   choiceValues = 1 : 2,
                   selected = 1 : 2)

## Read in the data
dat = reactive({
    if (is.null(input$imageFiles$datapath)) NULL
    else readFileList(input$imageFiles$datapath, 
                      fixBF = TRUE, 
                      fixT2 = TRUE)
})
    
## if necessary filter the data by the checkboxes
rval = reactive({
## If they uncheck everything, then return NULL, 
##or if the data hasn't been read in
    if (length(input$types)  == 0 |  
        length(input$levels) == 0 | 
        is.null(dat())) NULL
    else {
        fdat = dat()
        ## If everything is selected, then don't filter
        if (length(input$levels) != 5){
            lvls = as.numeric(input$levels)
            fdat = fdat %>% filter(level %in% lvls)
        }
        ## If everything is selected, then don't filter
        if (length(input$types) != 5) {
            tpes = as.numeric(input$types)
            fdat = fdat %>% filter(type %in% tpes)
        }
        fdat
    }
})

## If possible, flatten the data
rvalFlat = reactive({
    ## If it's null then don't do anything
    if(is.null(rval())) NULL
    else spreadROIs(rval())
})

## Display for the tidy and flattened data
output$displayTable = renderDataTable({rval()})
output$displayTableFlat = renderDataTable(rvalFlat())
```

Messages
===
```{r}
## Message of whether the data is loaded
output$imageDataStatus = renderText({
    if (is.null(dat())) "Data is not loaded"
    else "Data is loaded"
})


textOutput("imageDataStatus") 

## Download the data
output$downloadData = downloadHandler(
    filename = function() {"tidyFormat.csv"},
    content = function(file) write.csv(rval(), file, 
                                       row.names = FALSE)
)
    
output$downloadDataFlat = downloadHandler(
    filename = function() {"flatFormat.csv"},
    content = function(file) write.csv(rvalFlat(), 
                                       file, 
                                       row.names = FALSE)
)

```


Tidy data
===
```{r}
dataTableOutput("displayTable")
```

Flat data
===
```{r}
dataTableOutput("displayTableFlat")
```

Download
===
You can download the data here after you have loaded it.

```{r}
downloadLink("downloadData", "Download the tidy data")
br()
downloadLink("downloadDataFlat", "Download the flat data")
```
