---
title: "Visualize MRICloud Output"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE, cache = FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(MRIcloudT1volumetrics)
library(sunburstR)
library(treemap)
library(RColorBrewer)
library("magrittr")
library(D3partitionR)
## Get the hierarchy data
hierarchyFile = "multilevel_lookup_table.txt"
hierarchy = read.table(hierarchyFile, header = TRUE, 
                  stringsAsFactors = FALSE, 
                  na.strings = "xxxx",
                  fill = TRUE
                  ) %>% 
  select(-modify.) 

names(hierarchy) = c("index", "roi", 
                     "alevel4", "alevel3", "alevel2", "alevel1",
                     "blevel4", "blevel3", "blevel2", "blevel1")

## There as some blank lines and NAs where the whole row has to be 
## Deleted
hierarchy = hierarchy %>% 
    filter(!is.na(alevel3)) %>% 
    filter(alevel3 != "")

color_list = rep(brewer.pal(12, 'Set3'), 40)
```

input data {.sidebar}
===

Input your MRICould output to visualize it.
```{r}

fileInput("imageFiles", "Select a MRICloud Output File.", multiple = FALSE)

dat = reactive({
        if (is.null(input$imageFiles$datapath)) NULL
        else {
            input$imageFiles$datapath %>% 
            readSubject() %>%
            subject2df() %>%
            addSubjectICV() %>%
            addSubjectTBV() %>%
            fixBasalForebrain() %>%
            fixTarget2()
        }
    })

smry = reactive({
    if (is.null(dat())) {
    smry =  data.frame(
         normalizedVolume = 1,
         alevel1 = 'input data',
         alevel2 = 'input data',
         alevel3 = 'input data', 
         alevel4 = 'input data', 
         roi = 'input data'
     )   
    }
    else {
        dat() %>% 
            filter(type == 1, level == 5) %>%
            left_join(hierarchy, by = "roi") %>%
            mutate(
                normalizedVolume = volume / tbv * 100
            ) %>%
            filter(!is.na(alevel1))
    }
})

```

Interactive sunburst
===
```{r}
renderD3partitionR({
    D3partitionR() %>%
        add_data(smry(),
                 count = 'normalizedVolume',
                 steps=c('alevel1',
                         'alevel2', 
                         'alevel3', 
                         'alevel4', 
                         'roi'),
             tooltip = c('name', 'normalizedVolume'),
             aggregate_fun = list(normalizedVolume = sum)) %>%
    set_discrete_color_scale(color_list) %>%
    set_legend_parameters(visible = FALSE) %>%
    plot()
})
```


Interactive treemap
===
```{r}
renderD3partitionR({
    D3partitionR() %>%
        add_data(smry(),
                 count = 'normalizedVolume',
                 steps=c('alevel1',
                         'alevel2', 
                         'alevel3', 
                         'alevel4', 
                         'roi'),
             tooltip = c('name', 'normalizedVolume'),
             aggregate_fun = list(normalizedVolume = sum)) %>%
    set_discrete_color_scale(color_list) %>%
    set_chart_type('treemap') %>%
    set_legend_parameters(visible = FALSE) %>%
    plot()
})
```


Interactive circlemap
===
```{r}
renderD3partitionR({
    D3partitionR() %>%
        add_data(smry(),
                 count = 'normalizedVolume',
                 steps=c('alevel1',
                         'alevel2', 
                         'alevel3', 
                         'alevel4', 
                         'roi'),
             tooltip = c('name', 'normalizedVolume'),
             aggregate_fun = list(normalizedVolume = sum)) %>%
    set_discrete_color_scale(color_list) %>%
    set_chart_type('circle_treemap') %>%
    set_legend_parameters(visible = FALSE) %>%
    plot()
})
```

Partition chart
===
```{r}
renderD3partitionR({
    D3partitionR() %>%
        add_data(smry(),
                 count = 'normalizedVolume',
                 steps=c('alevel1',
                         'alevel2', 
                         'alevel3', 
                         'alevel4', 
                         'roi'),
             tooltip = c('name', 'normalizedVolume'),
             aggregate_fun = list(normalizedVolume = sum)) %>%
    set_discrete_color_scale(color_list) %>%
    set_chart_type('partition_chart') %>%
    set_legend_parameters(visible = FALSE) %>%
    plot()
})
```

